# === Netlify Configuration File ===
# ... your existing [build] settings ...

# --- SEO Redirect Rules ---

# Rule 1: Enforce Trailing Slashes
[[redirects]]
  from = "/:slug"
  to = "/:slug/"
  status = 301
  force = false
  conditions = {path = "!/\\.html$|/\\.xml$|/\\.txt$|/\\.png$|/\\.jpg$|/\\.svg$|/\\.mp4$|/\\.js$|/\\.css$"}

# Rule 2: Redirect old /documentation/ URL to /features/
[[redirects]]
  from = "/documentation/"
  to = "/features/"
  status = 301 # Permanent Redirect