# === Netlify Configuration File ===

[build]
  # FIX: Change the command from "npm run start" to "npm run build"
  # This tells Netlify to run the finite build process, not the infinite development server.
  command = "npm run build" 
  publish = "_site"

# --- SEO Redirect Rules ---

# Rule 1: Redirect the old specific .html page to its new canonical URL
[[redirects]]
  from = "/documentation.html"
  to = "/features/"
  status = 301 # Permanent Redirect

# Rule 2: Redirect the old clean URL to its new canonical URL
[[redirects]]
  from = "/documentation/"
  to = "/features/"
  status = 301 # Permanent Redirect

# Rule 3: Enforce Trailing Slashes sitewide for consistency
[[redirects]]
  from = "/:slug"
  to = "/:slug/"
  status = 301
  conditions = {path = "!/\\.html$|/\\.xml$|/\\.txt$|/\\.png$|/\\.jpg$|/\\.svg$|/\\.mp4$|/\\.js$|/\\.css$"}